const $ = s=>document.querySelector(s); const $$ = s=>document.querySelectorAll(s);
let CART=[];
function beep(type='triangle', seq=[880,1175,1320], dur=0.06){try{const A=new (window.AudioContext||window.webkitAudioContext)();let t=A.currentTime;seq.forEach(f=>{const o=A.createOscillator(),g=A.createGain();o.type=type;o.frequency.value=f;o.connect(g);g.connect(A.destination);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.3,t+0.01);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);o.start(t);o.stop(t+dur);t+=dur*0.4;});}catch(e){}}
window.addEventListener('DOMContentLoaded',()=>{beep('sawtooth',[440,660,990],0.08);$('#btnWA').addEventListener('click',()=>{beep('triangle',[1200,1600],0.06);openWA();});$('#btnCart').addEventListener('click',openDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);$('#btnCheckout').addEventListener('click',checkout); $$('.btn.add').forEach(b=>{b.addEventListener('click',()=>{const id=b.dataset.id,nombre=b.dataset.nombre,precio=Number(b.dataset.precio);const it=CART.find(x=>x.id===id)||(CART.push({id,nombre,precio,cant:0}),CART.find(x=>x.id===id));it.cant++;renderCart();beep('triangle',[700,980],0.05);});});});
function openDrawer(){$('#drawer').classList.add('open');} function closeDrawer(){$('#drawer').classList.remove('open');}
function renderCart(){const list=$('#cartItems');list.innerHTML='';let total=0;CART.forEach((it,idx)=>{total+=it.precio*it.cant;const row=document.createElement('div');row.className='cart-item';row.innerHTML=`<div><div class="name">${it.nombre}</div><div class="muted">$${it.precio} x ${it.cant}</div></div><div class="qty"><button data-i="${idx}" data-d="-1">−</button><button data-i="${idx}" data-d="1">＋</button></div>`;list.appendChild(row);});$('#cartTotal').textContent='$'+total.toFixed(2);$('#cartCount').textContent=CART.reduce((a,b)=>a+b.cant,0); $$('#cartItems button').forEach(btn=>{btn.onclick=()=>{const i=Number(btn.dataset.i),d=Number(btn.dataset.d);CART[i].cant+=d; if(CART[i].cant<=0) CART.splice(i,1); renderCart();beep('square',[520],0.05);};});}
function openWA(){const number='5355001648';const url=`https://wa.me/${number}`;window.open(url,'_blank');}
function checkout(){if(CART.length===0) return; const total=CART.reduce((s,i)=>s+i.precio*i.cant,0); const lines=CART.map(i=>`• ${i.nombre} — $${(i.precio*i.cant).toFixed(2)}`); const famName=prompt('Nombre y apellido del familiar (para el envío):',''); const famPhone=prompt('Teléfono del familiar:',''); const famAddr=prompt('Dirección de envío del familiar:',''); const text=`Hola Cubaclick! 👋%0AQuiero confirmar este pedido:%0A${lines.join('%0A')}%0ATotal: $${total.toFixed(2)} USD%0AEnvío a: ${famAddr}%0ATeléfono: ${famPhone}%0ANombre y apellido: ${famName}`; const number='5355001648'; const wa=`https://wa.me/${number}?text=${text}`; beep('triangle',[1320,1760],0.06); window.open(wa,'_blank');}
$$('.cta-row a').forEach(a=>a.addEventListener('click',()=>beep('triangle',[900],0.05)));
$$('.remesas .btn').forEach(b=>b.addEventListener('click',()=>beep('triangle',[900],0.05)));
